app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

Categories:
    type:     rest
    resource: '@AppBundle/Controller/CategoriesController.php'

Products:
    type:     rest
    resource: '@AppBundle/Controller/ProductsController.php'