app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

Brands:
    type:     rest
    resource: '@AppBundle/Controller/BrandsController.php'

Categories:
    type:     rest
    resource: '@AppBundle/Controller/CategoriesController.php'